function project1extendeddata = import_data(workbookFile, sheetName, dataLines)
%import_data Import data from a spreadsheet
%  PROJECT1EXTENDEDDATA = import_data(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  PROJECT1EXTENDEDDATA = import_data(FILE, SHEET) reads from the
%  specified worksheet.
%
%  PROJECT1EXTENDEDDATA = import_data(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  project1extendeddata = importfile("/Users/yg/code/github/mathematical-methods-en-585-615/project_1/project_1_extended_data.xlsx", "Sheet1", [1, 71]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Feb-2021 11:23:04

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 71];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "Time", "Concentration"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
project1extendeddata = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    project1extendeddata = [project1extendeddata; tb]; %#ok<AGROW>
end

end